"""Add foreign key fixes

Revision ID: faa332eaaaa3
Revises: fde8b05d87e4
Create Date: 2024-07-18 19:22:07.505440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa332eaaaa3'
down_revision = 'fde8b05d87e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_segments', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_image_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_image_segment_image_id', 'image', ['image_id'], ['id'])
        batch_op.drop_column('crop_box')
        batch_op.drop_column('predicted_iou')
        batch_op.drop_column('stability_score')
        batch_op.drop_column('bbox')
        batch_op.drop_column('area')
        batch_op.drop_column('point_coords')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_coords', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('area', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bbox', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('stability_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('predicted_iou', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('crop_box', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint('fk_image_segment_image_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_image_id', 'image', ['image_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('num_segments')

    # ### end Alembic commands ###
