"""Add new fields for segmentation data

Revision ID: fcd10e93b627
Revises: 61a413241345
Create Date: 2024-07-18 17:45:48.115429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd10e93b627'
down_revision = '61a413241345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('processed_filename', sa.String(length=256), nullable=True),
    sa.Column('predicted_iou', sa.Float(), nullable=True),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('bbox', sa.String(length=128), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('point_coords', sa.String(length=256), nullable=True),
    sa.Column('crop_box', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_segment')
    # ### end Alembic commands ###
