"""Add foreign key to ImageSegment

Revision ID: fde8b05d87e4
Revises: fcd10e93b627
Create Date: 2024-07-18 18:22:04.169207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde8b05d87e4'
down_revision = 'fcd10e93b627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_image_id', 'image', ['image_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
